services:
  push_notification_service:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app
    image: push_notification_service
    container_name: push_notification_service_container
    command: uvicorn push_notification.asgi:application --host 0.0.0.0 --port 8000 --reload
    # command: daphne -b 0.0.0.0 -p 8000 push_notification.asgi:application
    # command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis

  redis:
    restart: always
    image: redis/redis-stack
    ports:
      - 6379:6379
    container_name: redis_notification_container

  celery:
    restart: always
    build:
      context: .
    volumes:
      - .:/app
    container_name: celery_notification_container
    command: celery -A push_notification worker -l INFO
    depends_on:
      - redis
      - push_notification_service
